Sysdig x Tidal Blog
falcosecurity/falco-website pull request #1017
Opened 2023-06-23 20:45 UTC by tropChaud

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind user-interface

> /kind content

> /kind translation

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area blog

> /area documentation

> /area videos

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2023-06-23 20:45 UTC, poiana commented
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/.github/blob/main/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [6ed9bd2](https://github.com/falcosecurity/falco-website/commits/6ed9bd277c372bd3e811dbe0f557f73db9d75e6b) Sysdig x Tidal Blog

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

2023-06-23 20:45 UTC, poiana commented
Welcome @tropChaud! It looks like this is your first PR to falcosecurity/falco-website 🎉

2023-06-23 20:45 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco-website/pull/1017#" title="Author self-approved">tropChaud</a>*
**Once this PR has been reviewed and has the lgtm label**, please assign leogr for approval. For more information see [the Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco-website).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/falco-website/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["leogr"]} -->

2023-06-23 20:50 UTC, tropChaud commented
This is my commit message

Signed-off-by: Scott Small scott.small@tidalcyber.com

2023-06-26 16:07 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco-website/pull/1017#" title="Author self-approved">tropChaud</a>*
**Once this PR has been reviewed and has the lgtm label**, please assign vjjmiras for approval. For more information see [the Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco-website).

<details open>
Needs approval from an approver in each of these files:

- **[content/OWNERS](https://github.com/falcosecurity/falco-website/blob/master/content/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["vjjmiras"]} -->

2023-06-26 16:20 UTC, Issif requested changes

2023-06-26 16:20 UTC, Issif commented on content/en/blog/tidal-registry-release/index.md
> +```
```suggestion
```yaml
```

To have syntax coloring

2023-06-26 16:20 UTC, Issif commented on content/en/blog/tidal-registry-release/index.md
> +```
```suggestion
```yaml
```

2023-06-26 16:20 UTC, Issif commented on content/en/blog/tidal-registry-release/index.md
> +```
```suggestion
```yaml
```

2023-06-26 16:20 UTC, Issif commented on content/en/blog/tidal-registry-release/index.md
> +```
```suggestion
```yaml
```

2023-06-26 16:20 UTC, Issif commented on content/en/blog/tidal-registry-release/index.md
> +```
```suggestion
```yaml
```

2023-06-26 16:20 UTC, Issif commented on content/en/blog/tidal-registry-release/index.md
> +```
```suggestion
```yaml
```

2023-06-26 16:20 UTC, Issif commented on content/en/blog/tidal-registry-release/index.md
> +```
```suggestion
```yaml
```

2023-06-26 18:54 UTC, Issif commented on content/en/blog/tidal-registry-release/index.md
> +date: 2023-06-23
```suggestion
date: 2023-06-27
```

2023-06-26 18:55 UTC, aijamalnk commented on content/en/blog/tidal-registry-release/index.md
> +date: 2023-06-23
```suggestion
date: 2023-06-26
```

2023-06-28 14:15 UTC, Issif approved these changes

2023-06-28 14:15 UTC, poiana commented
LGTM label has been added.  <details>Git tree hash: a43e6dff1d86d0d656188414388df82d2fb6b333</details>

2023-06-28 14:15 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco-website/pull/1017#pullrequestreview-1503214220" title="Approved">Issif</a>*, *<a href="https://github.com/falcosecurity/falco-website/pull/1017#" title="Author self-approved">tropChaud</a>*

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco-website).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[content/OWNERS](https://github.com/falcosecurity/falco-website/blob/master/content/OWNERS)~~ [Issif]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2023-06-28 14:15 UTC, merged