fix(content): edit aliases to be relative
falcosecurity/falco-website pull request #1174
Opened 2023-10-06 14:53 UTC by LucaGuerra

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area documentation

**What this PR does / why we need it**:

Still drawing inspiration from @vjjmiras 's wisdom here: https://github.com/falcosecurity/falco-website/pull/1155 . According to the [documentation](https://gohugo.io/content-management/urls/#aliases):

> An alias without a leading slash is relative to the current directory"

In English, navigating to `/about/falco` should redirect to `/about/`

In no circumstances `/docs/about/` should ever send you to `/ja/docs/about/`. This PR allows to better test this theory.

If this works properly, we can proceed to add the mounts shown in https://github.com/falcosecurity/falco-website/pull/1155 and so we can fill the missing multilang pages with the English ones.

**Which issue(s) this PR fixes**:

Part of https://github.com/falcosecurity/falco-website/issues/1175

Fixes #

**Special notes for your reviewer**:

2023-10-06 14:53 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco-website/pull/1174#" title="Author self-approved">LucaGuerra</a>*
**Once this PR has been reviewed and has the lgtm label**, please assign vjjmiras for approval. For more information see [the Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco-website).

<details open>
Needs approval from an approver in each of these files:

- **[content/OWNERS](https://github.com/falcosecurity/falco-website/blob/master/content/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["vjjmiras"]} -->

2023-10-06 15:21 UTC, LucaGuerra commented
Seems to work locally, but not when deployed :raised_eyebrow:

2023-10-06 15:26 UTC, vjjmiras commented
> Seems to work locally, but not when deployed :raised_eyebrow: 

You might be using a newer version than Netlify and have some bug fixed locally. Just a guess. On Monday I can have a look to the PR.

2023-10-06 15:28 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco-website/pull/1174#" title="Author self-approved">LucaGuerra</a>*
**Once this PR has been reviewed and has the lgtm label**, please assign leogr for approval. For more information see [the Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco-website).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/falco-website/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["leogr"]} -->

2023-10-06 16:26 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco-website/pull/1174#" title="Author self-approved">LucaGuerra</a>*
**Once this PR has been reviewed and has the lgtm label**, please assign vjjmiras for approval. For more information see [the Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco-website).

<details open>
Needs approval from an approver in each of these files:

- **[content/OWNERS](https://github.com/falcosecurity/falco-website/blob/master/content/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["vjjmiras"]} -->

2023-10-06 16:26 UTC, poiana commented
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/.github/blob/main/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [3489803](https://github.com/falcosecurity/falco-website/commits/3489803f08e2fa90e32b3606130ba6d30e77362d) Revert "test"
- [d0b8959](https://github.com/falcosecurity/falco-website/commits/d0b8959350d6304e37b49abacbd9a6cec3eaf76a) Revert "wip: check relative aliases"
- [1a45fc2](https://github.com/falcosecurity/falco-website/commits/1a45fc21ec871c2270dd0e5116383ad273ba530c) Revert "update(website): update hugo version"
- [a568762](https://github.com/falcosecurity/falco-website/commits/a568762b1afa3c7fae9b9e0878f03aae4ef3a632) Revert "fix(content): remove leading / from aliases when not necessary"

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

2023-10-06 16:29 UTC, poiana commented
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/.github/blob/main/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [3489803](https://github.com/falcosecurity/falco-website/commits/3489803f08e2fa90e32b3606130ba6d30e77362d) Revert "test"
- [d0b8959](https://github.com/falcosecurity/falco-website/commits/d0b8959350d6304e37b49abacbd9a6cec3eaf76a) Revert "wip: check relative aliases"
- [1a45fc2](https://github.com/falcosecurity/falco-website/commits/1a45fc21ec871c2270dd0e5116383ad273ba530c) Revert "update(website): update hugo version"
- [a568762](https://github.com/falcosecurity/falco-website/commits/a568762b1afa3c7fae9b9e0878f03aae4ef3a632) Revert "fix(content): remove leading / from aliases when not necessary"

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

2023-10-07 11:41 UTC, LucaGuerra commented
Seems to be working. A bit of testing is appreciated :sweat_smile:

2023-10-10 13:07 UTC, vjjmiras requested changes
Amazing job, @LucaGuerra.

I've just corrected 4 aliases to fix the following broken links:

```
https://deploy-preview-1174--falcosecurity.netlify.app/docs/configuration/
https://deploy-preview-1174--falcosecurity.netlify.app/docs/getting-started/running/
https://deploy-preview-1174--falcosecurity.netlify.app/docs/rules/supported-events/
https://deploy-preview-1174--falcosecurity.netlify.app/docs/rules/supported-fields/
```

2023-10-10 13:24 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco-website/pull/1174#" title="Author self-approved">LucaGuerra</a>*
**Once this PR has been reviewed and has the lgtm label**, please ask for approval from vjjmiras. For more information see [the Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco-website).

<details open>
Needs approval from an approver in each of these files:

- **[content/OWNERS](https://github.com/falcosecurity/falco-website/blob/master/content/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["vjjmiras"]} -->

2023-10-10 13:45 UTC, poiana commented
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/.github/blob/main/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [37cef73](https://github.com/falcosecurity/falco-website/commits/37cef73015efe5b8afb46852d133da1416be6d9d) fix(content): fix changelog index.md

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

2023-10-10 14:26 UTC, LucaGuerra commented
Great catch @vjjmiras ! I have updated other `index.md` files I found. I already updated `_index.md`'s but not those :)

2023-10-10 15:54 UTC, vjjmiras approved these changes
LGTM

2023-10-10 15:54 UTC, merged