wip: website restructuring, the "concepts" section [2/N]
falcosecurity/falco-website pull request #1421
Opened 2024-12-13 15:55 UTC by leogr

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind user-interface

/kind content

> /kind event

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area blog

/area documentation

> /area community

**What this PR does / why we need it**:

See https://github.com/falcosecurity/falco-website/issues/1365

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2024-12-13 15:55 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco-website/pull/1421#" title="Author self-approved">leogr</a>*

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco-website).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[content/OWNERS](https://github.com/falcosecurity/falco-website/blob/master/content/OWNERS)~~ [leogr]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2025-01-08 16:20 UTC, LucaGuerra commented on content/en/docs/concepts/event-sources/_index.md
> +2. Use the `-o engine.kind=nodriver` option.
Sounds unclear. Would any plugin generate syscalls?

2025-01-08 16:26 UTC, LucaGuerra commented on content/en/docs/concepts/event-sources/_index.md
> +When processing capture files, Falco can handle events from multiple sources without additional configuration.
Is this true? Don't we need the appropriate plugin installed?

2025-01-08 16:28 UTC, leogr commented on content/en/docs/concepts/event-sources/_index.md
> +2. Use the `-o engine.kind=nodriver` option.
It is technically feasible, but no plugins have implemented that yet. We may want to remove it for now.

@jasondellaluce wdyt?

2025-01-08 16:30 UTC, leogr commented on content/en/docs/concepts/event-sources/_index.md
> +When processing capture files, Falco can handle events from multiple sources without additional configuration.
It is somehow true since the source capability of the plugin is not required while requiring the plugin. However, the extraction capability will be necessary to extract fields. I will improve the text.

2025-01-13 11:34 UTC, leogr commented on content/en/docs/concepts/event-sources/_index.md
> +When processing capture files, Falco can handle events from multiple sources without additional configuration.
alert removed for now

2025-01-13 11:34 UTC, leogr commented on content/en/docs/concepts/event-sources/_index.md
> +2. Use the `-o engine.kind=nodriver` option.
rephrased

2025-01-13 13:58 UTC, Issif commented on content/en/docs/concepts/event-sources/_index.md
> +Each event source operates in an isolated thread, where events are generated, consumed, and evaluated by Falco’s rule engine. Rules are partitioned by event source, meaning each rule applies to a spe
```suggestion
Each event source operates in an isolated thread, where events are generated, consumed, and evaluated by Falco’s rule engine. Rules are partitioned by event source, meaning each rule applies to a specific source and is triggered exclusively by events from that source. 

{{% pageinfo color=warning %}}
Falco does not support correlating events from different sources.
{{% /pageinfo %}}
```

2025-01-13 14:05 UTC, Issif commented on content/en/docs/concepts/event-sources/_index.md
> +
```suggestion
This example enables only the `syscall` and `k8s_audit` sources. The `syscall` source is built into Falco and always enabled by default. In contrast, the `k8s_audit` source is provided by the `k8saudit` plugin, which must be properly configured in Falco beforehand. Before using this command, ensure that the `k8saudit` plugin has been properly configured in Falco.

{{% pageinfo color=info %}}
The `k8saudit` source is also available through different plugins: `k8saudit`, `k8saudit-aks`, `k8saudit-eks`, `k8saudit-gke` and `k8suadit-ovh`, choose the one fitting your environment. They all share the same set of rules.
{{% /pageinfo %}}
```

2025-01-13 14:11 UTC, Issif requested changes

2025-01-13 14:11 UTC, Issif commented on content/en/docs/concepts/event-sources/_index.md
> +### Using the `syscall` Source Without a Driver
```suggestion
### Using the `syscall` source without a driver
```

2025-01-13 14:11 UTC, Issif commented on content/en/docs/concepts/event-sources/_index.md
> +By default, Falco enables the `syscall` source and relies on a [kernel driver](/docs/concepts/event-sources/kernel/)) to capture events. However, there are times—such as when testing, debugging, or r
```suggestion
By default, Falco enables the `syscall` source and relies on a [kernel driver](/docs/concepts/event-sources/kernel/)) to capture events. However, there are times — such as when testing, debugging, or running plugins that generate `syscall` events — when you may want to run Falco without a driver.
```

2025-01-13 14:20 UTC, leogr commented on content/en/docs/concepts/event-sources/_index.md
> +
nice improvement! thank you

2025-01-13 15:00 UTC, Issif commented
/lgtm

2025-01-13 15:00 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco-website/pull/1421#issuecomment-2587339096" title="LGTM">Issif</a>*, *<a href="https://github.com/falcosecurity/falco-website/pull/1421#" title="Author self-approved">leogr</a>*

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco-website).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[content/OWNERS](https://github.com/falcosecurity/falco-website/blob/master/content/OWNERS)~~ [Issif,leogr]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2025-01-13 15:04 UTC, Issif approved these changes

2025-01-13 15:04 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco-website/pull/1421#pullrequestreview-2546912389" title="Approved">Issif</a>*, *<a href="https://github.com/falcosecurity/falco-website/pull/1421#" title="Author self-approved">leogr</a>*

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco-website).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[content/OWNERS](https://github.com/falcosecurity/falco-website/blob/master/content/OWNERS)~~ [Issif,leogr]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2025-01-13 15:04 UTC, merged