Update install script
falcosecurity/falco-website pull request #467
Opened 2021-06-24 09:42 UTC by chirabino

### Changes
- The script will install epel if not present
- The script will support Suse
- mobprobe command removed
- override instead of append to `falcosecurity.list` file.

### NOT in the script
I think that from version 0.28 a reload of the systemd manager configuration is needed.

### Notes
Except for Suse (which we tested in our test environment, on different version of Suse) we used the script a lot without any issues.

**Special notes for your reviewer**:
Thanks for your time :)

/cc @leodido 
/cc @leogr 

/kind content
/area documentation

2021-06-24 09:42 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco-website/pull/467#" title="Author self-approved">chirabino</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **fntlnz** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @fntlnz` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco-website).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/falco-website/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["fntlnz"]} -->

2021-06-24 09:42 UTC, poiana commented
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/falco-website/blob/master/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [4962195](https://github.com/falcosecurity/falco-website/commits/4962195f59bc20a19fc02a7e10cc35e86240fd14) Update install script

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

2021-06-24 09:42 UTC, poiana commented
Welcome @chirabino! It looks like this is your first PR to falcosecurity/falco-website 🎉

2021-06-24 09:49 UTC, chirabino commented
Signed-off-by: Domenico Chirabino

2021-06-24 10:13 UTC, leodido reviewed
Hello @chirabino!

You need to sign-off your commit :)

2021-06-29 13:19 UTC, leogr reviewed
Hey @chirabino 

thanks for taking care of this :pray: 

Just two questions at the moment.

Shall we update the script's sha256sum here :point_down: too?
https://github.com/falcosecurity/falco-website/blob/fa2d29eefa7139f8f8344820f9951998be625131/config.toml#L166

For the other question, see the comment below.

2021-06-29 13:21 UTC, leogr commented
> ### NOT in the script
> I think that from version 0.28 a reload of the systemd manager configuration is needed.

If necessary, please update the documentation.
Thank you!

2021-06-29 13:38 UTC, leogr commented on static/script/install
> -modprobe -r falco_probe
Or are we assuming that the systemd unit will take care of that?

To be clear, I agree we don't need modprobe here. I just wanted to understand which steps the users will have to follow.

2021-07-05 12:32 UTC, leogr commented
Hey @chirabino 

any news?

2021-07-07 09:21 UTC, chirabino commented
> Shall we update the script's sha256sum here 👇 too?
> 
> https://github.com/falcosecurity/falco-website/blob/fa2d29eefa7139f8f8344820f9951998be625131/config.toml#L166

@leogr I have created a PR: #478

2021-07-07 09:31 UTC, chirabino commented on static/script/install
> -modprobe -r falco_probe
systemd will take care of that.

2021-07-07 09:39 UTC, chirabino commented
> 
> 
> > ### NOT in the script
> > I think that from version 0.28 a reload of the systemd manager configuration is needed.
> 
> If necessary, please update the documentation.
> Thank you!

@leogr I have created a PR: #479

2021-07-07 10:07 UTC, leogr commented
> > Shall we update the script's sha256sum here point_down too?
> > https://github.com/falcosecurity/falco-website/blob/fa2d29eefa7139f8f8344820f9951998be625131/config.toml#L166
> 
> @leogr I have created a PR: #478

> > Shall we update the script's sha256sum here point_down too?
> > https://github.com/falcosecurity/falco-website/blob/fa2d29eefa7139f8f8344820f9951998be625131/config.toml#L166
> 
> @leogr I have created a PR: #478

Since the script has been updated by this PR, I believe it would be better to update the sha256sum directly here (instead of opening another PR). Is there any particular reason (that I might not consider) to make another PR?
If not, could you close the #478 and include the change in this PR, please?

2021-07-12 14:02 UTC, leogr requested changes
The sha256sum does not match:
```
❯ curl -o install_falco -s https://deploy-preview-467--falcosecurity.netlify.app/script/install                                  
❯ sha256sum install_falco
59201c1339cc53e86edcd7d2e7273e52f784b3cf7d4a3142059112b3b9062f6d  install_falco
```

2021-07-14 14:05 UTC, chirabino commented
> The sha256sum does not match:

@leogr you are right, I have update the sha256sum in a new commit. Sorry for that.

2021-08-18 10:17 UTC, leogr approved these changes
Overall looks good to me. Not completely sure if the new `install_suse` works in all cases (I have just tested the commons ones). Anyway, it's already a good improvement, so approved. 

Thank you!

2021-08-18 10:17 UTC, poiana commented
LGTM label has been added.  <details>Git tree hash: cf889803a9b7405843fc637215f9597c5435cba0</details>

2021-08-18 10:17 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco-website/pull/467#" title="Author self-approved">chirabino</a>*, *<a href="https://github.com/falcosecurity/falco-website/pull/467#pullrequestreview-732686392" title="Approved">leogr</a>*

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco-website).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/falcosecurity/falco-website/blob/master/OWNERS)~~ [leogr]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-08-18 15:54 UTC, leogr commented
/check-dco

2021-08-18 15:55 UTC, merged