Fission output type blog post
falcosecurity/falco-website pull request #484
Opened 2021-07-22 03:16 UTC by gauravgahlot

Signed-off-by: Gaurav Gahlot <gauravgahlot0107@gmail.com>

**What type of PR is this?**

/kind content

**Any specific area of the project related to this PR?**

/area blog

2021-07-22 03:16 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco-website/pull/484#" title="Author self-approved">gauravgahlot</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **rajakavitha1** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @rajakavitha1` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco-website).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/falco-website/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["rajakavitha1"]} -->

2021-07-22 03:16 UTC, poiana commented
Welcome @gauravgahlot! It looks like this is your first PR to falcosecurity/falco-website 🎉

2021-07-22 03:16 UTC, gauravgahlot commented
/assign

2021-07-22 05:13 UTC, Issif commented on content/en/blog/falcosidekick-reponse-engine-part-8-fission.md
> +> * [Kubernetes Response Engine, Part 7: Falcosidekick + Cloud Functions]({{< ref "/blog/falcosidekick-reponse-engine-part-7-cloud-functions" >}})
```suggestion
> * [Kubernetes Response Engine, Part 7 : Falcosidekick + Cloud Functions]({{< ref "/blog/falcosidekick-reponse-engine-part-7-cloud-functions" >}})
```

2021-07-25 11:44 UTC, Issif commented
/hold

We can't release this post before next version of falcosidekick

2021-08-18 10:10 UTC, leogr reviewed
Just found some minor issues, otherwise looks good to me! :clap:

2021-08-18 10:10 UTC, leogr commented on content/en/blog/falcosidekick-reponse-engine-part-8-fission.md
> +There are various ways to provision a local Kubernetes cluster such as, KinD, k3s, k0s, Minikube etc. We are going to
```suggestion
There are various ways to provision a local Kubernetes cluster such as KinD, k3s, k0s, Minikube, etc. We are going to
```

2021-08-18 10:10 UTC, leogr commented on content/en/blog/falcosidekick-reponse-engine-part-8-fission.md
> +In this blog post, we will cover using `Falcosidekick` and `Fission` to detect and delete a compromised pod in Kubernetes cluster.
```suggestion
In this blog post, we will cover using `Falcosidekick` and `Fission` to detect and delete a compromised pod in a Kubernetes cluster.
```

2021-08-18 10:10 UTC, leogr commented on content/en/blog/falcosidekick-reponse-engine-part-8-fission.md
> +We create a `ServiceAccount` with right to delete a Pod in any namespace, and we'll associate it to our function:
```suggestion
We create a `ServiceAccount` with rights to delete a Pod in any namespace, and we'll associate it to our function:
```

2021-08-18 10:10 UTC, leogr commented on content/en/blog/falcosidekick-reponse-engine-part-8-fission.md
> +With this really simple example, we got another way to create a Response Engine with amazing pieces of software from Open Source world.
```suggestion
With this really simple example, we got another way to create a Response Engine with amazing pieces of software from the Open Source world.
```

2021-08-18 10:29 UTC, Issif commented on content/en/blog/falcosidekick-reponse-engine-part-8-fission.md
> +date: 2021-07-22
Please update the date to a more recent one (after release of 2.24.0 of falcosidekick)

2021-08-29 08:44 UTC, Issif commented on content/en/blog/falcosidekick-reponse-engine-part-8-fission.md
> +date: 2021-08-19
```suggestion
date: 2021-08-29
```

2021-08-29 08:44 UTC, Issif requested changes
please update the date of the post

2021-08-29 21:38 UTC, Issif approved these changes

2021-08-29 21:39 UTC, poiana commented
LGTM label has been added.  <details>Git tree hash: 44a2c27fb6a47f4c575382cd229b1409aa4dba23</details>

2021-08-29 21:39 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco-website/pull/484#" title="Author self-approved">gauravgahlot</a>*, *<a href="https://github.com/falcosecurity/falco-website/pull/484#pullrequestreview-741153877" title="Approved">Issif</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **rajakavitha1** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @rajakavitha1` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco-website).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/falco-website/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["rajakavitha1"]} -->

2021-08-30 11:10 UTC, leogr approved these changes
LGTM

2021-08-30 11:10 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco-website/pull/484#" title="Author self-approved">gauravgahlot</a>*, *<a href="https://github.com/falcosecurity/falco-website/pull/484#pullrequestreview-741153877" title="Approved">Issif</a>*, *<a href="https://github.com/falcosecurity/falco-website/pull/484#pullrequestreview-741530903" title="Approved">leogr</a>*

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco-website).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/falcosecurity/falco-website/blob/master/OWNERS)~~ [leogr]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-08-31 07:40 UTC, Issif requested changes

2021-08-31 07:40 UTC, Issif commented on content/en/blog/falcosidekick-reponse-engine-part-8-fission.md
> +title: "Kubernetes Response Engine, Part 8: Falcosidekick + Fission"
```suggestion
title: "Kubernetes Response Engine, Part 9: Falcosidekick + Fission"
```

2021-08-31 07:40 UTC, Issif commented on content/en/blog/falcosidekick-reponse-engine-part-8-fission.md
> +slug: falcosidekick-reponse-engine-part-8-fission
```suggestion
slug: falcosidekick-reponse-engine-part-9-fission
```

2021-08-31 07:40 UTC, Issif commented on content/en/blog/falcosidekick-reponse-engine-part-8-fission.md
> +> * [Kubernetes Response Engine, Part 7 : Falcosidekick + Cloud Functions]({{< ref "/blog/falcosidekick-reponse-engine-part-7-cloud-functions" >}})
Can you add the part 8 with Flux v2 please

2021-08-31 07:40 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco-website/pull/484#" title="Author self-approved">gauravgahlot</a>*, *<a href="https://github.com/falcosecurity/falco-website/pull/484#pullrequestreview-741530903" title="Approved">leogr</a>*

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco-website).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/falcosecurity/falco-website/blob/master/OWNERS)~~ [leogr]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-08-31 09:52 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco-website/pull/484#" title="Author self-approved">gauravgahlot</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **leogr** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco-website).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/falco-website/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["leogr"]} -->

2021-08-31 09:52 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco-website/pull/484#" title="Author self-approved">gauravgahlot</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **leogr** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco-website).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/falco-website/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["leogr"]} -->

2021-08-31 10:05 UTC, Issif approved these changes

2021-08-31 10:05 UTC, poiana commented
LGTM label has been added.  <details>Git tree hash: afecdf26c827d0758c39d0463e6455e97c5b444e</details>

2021-08-31 10:05 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco-website/pull/484#" title="Author self-approved">gauravgahlot</a>*, *<a href="https://github.com/falcosecurity/falco-website/pull/484#pullrequestreview-742529995" title="Approved">Issif</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **leogr** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco-website).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/falco-website/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["leogr"]} -->

2021-08-31 10:42 UTC, poiana commented
New changes are detected. LGTM label has been removed.

2021-08-31 10:42 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco-website/pull/484#" title="Author self-approved">gauravgahlot</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **leogr** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco-website).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/falco-website/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["leogr"]} -->

2021-08-31 10:42 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco-website/pull/484#" title="Author self-approved">gauravgahlot</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **leogr** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco-website).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/falco-website/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["leogr"]} -->

2021-09-01 04:57 UTC, gauravgahlot commented
Needs a rebase after #492 is merged.

2021-09-03 14:19 UTC, danpopSD commented
/lgtm
/approve

2021-09-03 14:19 UTC, poiana commented
LGTM label has been added.  <details>Git tree hash: ebfc731b5af7fbbdef0318e5c26dbfb0018c92c5</details>

2021-09-03 14:19 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco-website/pull/484#issuecomment-912575373" title="Approved">danpopSD</a>*, *<a href="https://github.com/falcosecurity/falco-website/pull/484#" title="Author self-approved">gauravgahlot</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **leogr** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco-website).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/falco-website/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["leogr"]} -->

2021-09-06 07:13 UTC, leogr approved these changes

2021-09-06 07:13 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco-website/pull/484#issuecomment-912575373" title="Approved">danpopSD</a>*, *<a href="https://github.com/falcosecurity/falco-website/pull/484#" title="Author self-approved">gauravgahlot</a>*, *<a href="https://github.com/falcosecurity/falco-website/pull/484#pullrequestreview-746882525" title="Approved">leogr</a>*

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco-website).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/falcosecurity/falco-website/blob/master/OWNERS)~~ [leogr]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-09-08 16:37 UTC, leogr commented
/hold cancel

2021-09-08 16:37 UTC, merged