add training section
falcosecurity/falco-website pull request #497
Opened 2021-09-29 11:32 UTC by pabloopez

hi Falco team,

here are the proposed changes to embed the 3 current Falco hands-on labs in the website. One of the labs was released weeks ago and for the other two there's going to be a PR with changes to fix them. So, I believe is a good idea to start moving this at the same time for you to test the proposed changes. 

Thanks for your time! :) 

**What type of PR is this?**

/kind user-interface

/kind content

**Any specific area of the project related to this PR?**

/area training

**What this PR does / why we need it**:

This PR creates a new section in the Falco website to host the hands-on labs. It creates a new section with an introduction to the content with links to one different page for every lab. This way we avoid loading the lab if the user is just viewing the intro. And this way we keep Katacoda infra usage low.

2021-09-29 11:33 UTC, poiana commented
@pabloopez: The label(s) `area/training` cannot be applied, because the repository doesn't have them.

<details>

In response to [this](https://github.com/falcosecurity/falco-website/pull/497):

>hi Falco team,
>
>here are the proposed changes to embed the 3 current Falco hands-on labs in the website. One of the labs was released weeks ago and for the other two there's going to be a PR with changes to fix them. So, I believe is a good idea to start moving this at the same time for you to test the proposed changes. 
>
>Thanks for your time! :) 
>
>**What type of PR is this?**
>
>/kind user-interface
>
>/kind content
>
>**Any specific area of the project related to this PR?**
>
>/area training
>
>**What this PR does / why we need it**:
>
>This PR creates a new section in the Falco website to host the hands-on labs. It creates a new section with an introduction to the content with links to one different page for every lab. This way we avoid loading the lab if the user is just viewing the intro. And this way we keep Katacoda infra usage low.
>


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-09-29 11:33 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco-website/pull/497#" title="Author self-approved">pabloopez</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **kris-nova** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @kris-nova` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco-website).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/falco-website/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["kris-nova"]} -->

2021-09-29 11:37 UTC, pabloopez commented
Find here a [preview of the changes](https://giphy.com/embed/YIk7RbtUzi8wgFkYRC), not great resolution but it helps to get an idea if you do not want to test it. I checked with `make serve` that all the changes are working fine.

2021-09-29 16:51 UTC, mstemm approved these changes
I'm not sure about the context, but it sounds like @pabloopez talked to other maintainers about adding a training/labs section. @pabloopez, which other maintainers did you talk to? But I did review it using make serve and it looks great.

2021-09-29 16:51 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco-website/pull/497#pullrequestreview-766955990" title="Approved">mstemm</a>*, *<a href="https://github.com/falcosecurity/falco-website/pull/497#" title="Author self-approved">pabloopez</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **kris-nova** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @kris-nova` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco-website).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/falco-website/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["kris-nova"]} -->

2021-09-29 16:51 UTC, poiana commented
LGTM label has been added.  <details>Git tree hash: 6e7625da5b1d5ec71380d18875171b1bb7ebcec6</details>

2021-09-29 18:34 UTC, radhikapc requested changes
minor suggestions

2021-09-29 18:34 UTC, radhikapc commented on layouts/partials/labs.html
> +    <p>General introduction to Falco in single Linux hosts. Learn how to install Falco with Docker, and detect threads
General introduction to Falco running in single Linux hosts. Learn how to install Falco with Docker, and detect threads, such as:

2021-09-29 18:34 UTC, radhikapc commented on layouts/partials/labs.html
> +    <p>This lab is the best place to start your Runtime Security jurney!</p>
This lab is the best place to start your Runtime Security journey!

2021-09-29 18:34 UTC, radhikapc commented on layouts/partials/labs.html
> +    <p>Play the both the intruder & sysadmin roles and detect a Rogue attack</p>
Let us roleplay both the intruder and sysadmin roles and detect a Rogue attack.

2021-09-29 18:34 UTC, radhikapc commented on layouts/partials/labs.html
> +    <p>Falco is not just about Runtime Detection, you can perform automated actions to mitigate threads automatically.
Falco is not just about Runtime Detection.  You can also perform automated actions to mitigate threads automatically.

2021-09-29 18:34 UTC, radhikapc commented on layouts/partials/labs.html
> +    <p>In this lab you will learn how to deploy Falco with Falcosidekick and Kubeless. Stop a running pod when you
In this lab, you will learn how to deploy Falco with Falcosidekick and Kubeless. Stop the running pod when you detect a security thread!

2021-09-29 19:51 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco-website/pull/497#" title="Author self-approved">pabloopez</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **radhikapc** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco-website).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/falco-website/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["radhikapc"]} -->

2021-09-29 19:53 UTC, pabloopez commented
Thank @radhikapc for your suggestions, I included a new commit with those changes.

2021-09-29 20:21 UTC, radhikapc approved these changes
LGTM

2021-09-29 20:21 UTC, poiana commented
LGTM label has been added.  <details>Git tree hash: bc04137999c8da8057c014fd26eb0d8d0895ce2f</details>

2021-09-29 20:21 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco-website/pull/497#" title="Author self-approved">pabloopez</a>*, *<a href="https://github.com/falcosecurity/falco-website/pull/497#pullrequestreview-767150236" title="Approved">radhikapc</a>*

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco-website).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/falcosecurity/falco-website/blob/master/OWNERS)~~ [radhikapc]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-09-29 20:21 UTC, merged

2021-09-29 20:37 UTC, pabloopez commented
> I'm not sure about the context, but it sounds like @pabloopez talked to other maintainers about adding a training/labs section. @pabloopez, which other maintainers did you talk to? But I did review it using make serve and it looks great.

Hi @mstemm, thanks for your time to review this. Your question sounds reasonable to me. Let me add more context:
- An [issue](https://github.com/falcosecurity/evolution/issues/70) was opened in `falco/evolution` to discuss the possibility of unarchiving the existing Falco hands-on labs. 
- Some weeks ago in one of the Falco Community Calls, I introduced the possibility to embed the labs into the Falco website. It was registered in the meeting [agenda](https://hackmd.io/3qYPnZPUQLGKCzR14va_qg?edit) (please, check date: 2021-05-26). 
 
@mstemm  you can find there a list of the assistants, some of them are maintainers of this repository too. If I remember well, I even shared a mockup (slightly different to the final result committed here) to show how we can embed the labs in the Falco website. 

Let me know if more clarification is required to proceed. Thank you.

2021-09-30 15:37 UTC, mstemm commented
No other info needed, I read the issue and I'm all caught up now. Thanks!