new(blog): gVisor and Falco tutorial
falcosecurity/falco-website pull request #677
Opened 2022-09-01 21:15 UTC by vjjmiras

Co-authored-by: Luca Guerra <luca@guerra.sh>
Co-authored-by: Lorenzo Susini <susinilorenzo1@gmail.com>
Co-authored-by: Vicente J. Jiménez Miras <vjjmiras@gmail.com>

Signed-off-by: Vicente J. Jiménez Miras <vjjmiras@gmail.com>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind user-interface

/kind content

> /kind translation

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area blog

> /area documentation

> /area videos

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2022-09-01 21:16 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco-website/pull/677#" title="Author self-approved">vjjmiras</a>*
**Once this PR has been reviewed and has the lgtm label**, please assign issif for approval by writing `/assign @issif` in a comment. For more information see:[The Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco-website).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/falco-website/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["issif"]} -->

2022-09-01 21:24 UTC, vjjmiras commented
/hold

2022-09-08 20:27 UTC, Issif requested changes

2022-09-08 20:27 UTC, Issif commented on content/en/blog/intro-gvisor-falco/index.md
> +date: 2022-09-01
date to update

2022-09-09 07:33 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco-website/pull/677#" title="Author self-approved">vjjmiras</a>*
**Once this PR has been reviewed and has the lgtm label**, please ask for approval from issif by writing `/assign @issif` in a comment. For more information see:[The Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco-website).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/falco-website/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["issif"]} -->

2022-09-09 10:42 UTC, vjjmiras commented on content/en/blog/intro-gvisor-falco/index.md
> +date: 2022-09-01
👍🏼

2022-09-15 12:45 UTC, Issif approved these changes

2022-09-15 12:45 UTC, poiana commented
LGTM label has been added.  <details>Git tree hash: 0936a1b9257beddf29f0f7df63f7d826bd62c538</details>

2022-09-15 12:45 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco-website/pull/677#pullrequestreview-1109123586" title="Approved">Issif</a>*, *<a href="https://github.com/falcosecurity/falco-website/pull/677#" title="Author self-approved">vjjmiras</a>*

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco-website).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/falcosecurity/falco-website/blob/master/OWNERS)~~ [Issif]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-09-15 12:47 UTC, vjjmiras commented
/unhold

2022-09-15 12:48 UTC, merged