Separate gRPC Config section from the parent page
falcosecurity/falco-website pull request #768
Opened 2022-12-13 16:20 UTC by vjjmiras

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind user-interface

/kind content

> /kind translation

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area blog

/area documentation

> /area videos

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2022-12-13 16:21 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco-website/pull/768#" title="Author self-approved">vjjmiras</a>*
**Once this PR has been reviewed and has the lgtm label**, please assign issif for approval by writing `/assign @issif` in a comment. For more information see [the Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco-website).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/falco-website/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["issif"]} -->

2022-12-16 13:38 UTC, Issif requested changes

2022-12-16 13:38 UTC, Issif commented on content/en/docs/grpc/grpc-config.md
> +as show in the next section.
```suggestion
as shown in the next section.
```

2022-12-16 13:38 UTC, Issif commented on content/en/docs/grpc/grpc-config.md
> +
```suggestion

```

2022-12-16 18:25 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco-website/pull/768#" title="Author self-approved">vjjmiras</a>*
**Once this PR has been reviewed and has the lgtm label**, please ask for approval from issif by writing `/assign @issif` in a comment. For more information see [the Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco-website).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/falco-website/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["issif"]} -->

2022-12-16 18:29 UTC, vjjmiras commented
Thanks, @Issif. I applied all your suggestions.

2022-12-16 18:36 UTC, Issif approved these changes

2022-12-16 18:36 UTC, poiana commented
LGTM label has been added.  <details>Git tree hash: 1b63dfe8d2db4b7ac0c1763bdafdb8cd2115405b</details>

2022-12-16 18:36 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco-website/pull/768#pullrequestreview-1221289668" title="Approved">Issif</a>*, *<a href="https://github.com/falcosecurity/falco-website/pull/768#" title="Author self-approved">vjjmiras</a>*

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco-website).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/falcosecurity/falco-website/blob/master/OWNERS)~~ [Issif]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-12-16 18:37 UTC, merged