fix: improve Debian instructions
falcosecurity/falco-website pull request #816
Opened 2023-02-14 16:24 UTC by sgaist

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

 /kind cleanup

> /kind design

> /kind user-interface

> /kind content

> /kind translation

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area blog

/area documentation

> /area videos

**What this PR does / why we need it**:

This PR improves the Debian installation instructions as they are currently relying on a deprecated and soon to be removed tool (apt-key).

The refactored instructions follow best practice in terms of apt source handling to improve the system security as well as working as a power user rather than root.

**Special notes for your reviewer**:

Nothing particular

2023-02-14 16:24 UTC, poiana commented
Welcome @sgaist! It looks like this is your first PR to falcosecurity/falco-website 🎉

2023-02-14 16:24 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco-website/pull/816#" title="Author self-approved">sgaist</a>*
**Once this PR has been reviewed and has the lgtm label**, please assign vjjmiras for approval. For more information see [the Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco-website).

<details open>
Needs approval from an approver in each of these files:

- **[content/OWNERS](https://github.com/falcosecurity/falco-website/blob/master/content/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["vjjmiras"]} -->

2023-03-30 14:57 UTC, Issif commented
Can you rebase your PR please, and sorry for the delay, we're in a full revamp of the website.

2023-03-30 15:59 UTC, sgaist commented
Sure thing and no worries

2023-03-30 16:02 UTC, vjjmiras commented
@sgaist The new procedure to add a key, do you know from which Debian version it is compatible?

2023-03-31 08:09 UTC, sgaist commented
@vjjmiras AFAIK, the support for `signed-by` is available since apt 1.1.

The key management instructions here are valid for at least Debian 7 (at the time of writing).
With Debian 6, you start getting in trouble because of TLS but you can still copy the file over and continue from there. There will be other warnings related to public key availability though.
That said, Falco cannot be installed as is on these old version of versions of Debian because of the base requirements it has.

One side question, should there be instructions to install `apt-transport-https` ? Beside curl and gpg, this package is mandatory to access the Debian server.

2023-04-27 13:01 UTC, vjjmiras requested changes
@sgaist, I've been testing the changes in other versions of Debian and you're right, the command works, but there are bigger issues to be concerned about, like the expired keys for the repositories.

Regarding the `apt-transport-https`, I found it is not necessary for Debian 10 and newer distributions, so I added a little change to incorporate your suggestion.

2023-04-27 13:11 UTC, sgaist commented
@vjjmiras about the key expiration, AFAIK, you will get an error message when the key has expired whether you use the new or old way to do handle them.

Do you mean you would add a note telling the user that they have to update the key when expiration happens ?

2023-04-27 16:14 UTC, vjjmiras requested changes
I just realized I left some quotes open, my bad. The suggestions should fix it.

2023-04-27 16:14 UTC, vjjmiras commented on content/en/docs/getting-started/installation.md
> +    sudo apt-get update -y
```suggestion
    ```
```

2023-04-27 16:14 UTC, vjjmiras commented on content/en/docs/getting-started/installation.md
>      ```
```suggestion
```

2023-04-27 16:14 UTC, vjjmiras commented on content/en/docs/getting-started/installation.md
> +    > sudo apt-get install apt-transport-https
```suggestion
    > sudo apt-get install apt-transport-https
    
```

2023-04-27 16:15 UTC, vjjmiras commented
> @vjjmiras about the key expiration, AFAIK, you will get an error message when the key has expired whether you use the new or old way to do handle them.
> 
> Do you mean you would add a note telling the user that they have to update the key when expiration happens ?

No, I just meant that if they still maintain so older systems, they have bigger concerns than how the repository key is deployed :-)

2023-04-28 08:23 UTC, poiana commented
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/.github/blob/main/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [faa638a](https://github.com/falcosecurity/falco-website/commits/faa638a6c5fe1b4533709c1ed67e42bae9ef6bf5) doc: fix removed instruction

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

2023-04-28 08:28 UTC, sgaist commented
> I just realized I left some quotes open, my bad. The suggestions should fix it.

Almost ! :-D

> > > @vjjmiras about the key expiration, AFAIK, you will get an error message when the key has expired whether you use the new or old way to do handle them.
> > >
> > Do you mean you would add a note telling the user that they have to update the key when expiration happens ?
> 
> No, I just meant that if they still maintain so older systems, they have bigger concerns than how the repository key is deployed :-)

Ok, now I see your point :-)

2023-04-28 15:27 UTC, vjjmiras approved these changes
LGTM

2023-04-28 15:27 UTC, poiana commented
LGTM label has been added.  <details>Git tree hash: d8817abe08cca50be7cc49b2d9a92d0c7e62391e</details>

2023-04-28 15:27 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco-website/pull/816#" title="Author self-approved">sgaist</a>*, *<a href="https://github.com/falcosecurity/falco-website/pull/816#pullrequestreview-1406174961" title="Approved">vjjmiras</a>*

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco-website).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[content/OWNERS](https://github.com/falcosecurity/falco-website/blob/master/content/OWNERS)~~ [vjjmiras]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2023-04-28 15:28 UTC, merged