Update falco-0-26-2.md
falcosecurity/falco-website pull request #971
Opened 2023-05-23 09:24 UTC by qinzhiben11

Modify incorrect vocabulary

Signed-off-by: qinzhiben@uniontech.com

2023-05-23 09:24 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco-website/pull/971#" title="Author self-approved">qinzhiben11</a>*
**Once this PR has been reviewed and has the lgtm label**, please assign vjjmiras for approval. For more information see [the Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco-website).

<details open>
Needs approval from an approver in each of these files:

- **[content/OWNERS](https://github.com/falcosecurity/falco-website/blob/master/content/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["vjjmiras"]} -->

2023-05-24 01:46 UTC, qinzhiben11 commented
@mstemm @vjjmiras 
Please help to review. 
Thank you

2023-05-31 09:26 UTC, vjjmiras requested changes
Hey @qinzhiben11,

Thank you for your submission. I've realized there are many Markdown headers that were not correctly defined in this translation.
Like I suggested in your submission - it still requires you to approve it-, could you fix those too? Thank you in advance!

2023-05-31 09:26 UTC, vjjmiras commented on content/zh-cn/blog/falco-0-26-2.md
> +##接下来做什么?
```suggestion
## 接下来做什么?
```

2023-06-02 06:32 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco-website/pull/971#" title="Author self-approved">qinzhiben11</a>*
**Once this PR has been reviewed and has the lgtm label**, please ask for approval from vjjmiras. For more information see [the Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco-website).

<details open>
Needs approval from an approver in each of these files:

- **[content/OWNERS](https://github.com/falcosecurity/falco-website/blob/master/content/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["vjjmiras"]} -->

2023-06-02 06:33 UTC, qinzhiben11 commented
hi @vjjmiras ，Thank you for your suggestion. I have taken and made the necessary modifications.

2023-06-23 12:36 UTC, vjjmiras commented
Thank you @qinzhiben11. Could you rebase your commits, so it can be merged?

2023-07-10 12:13 UTC, vjjmiras approved these changes
LGTM

2023-07-10 12:13 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falco-website/pull/971#" title="Author self-approved">qinzhiben11</a>*, *<a href="https://github.com/falcosecurity/falco-website/pull/971#pullrequestreview-1521945977" title="Approved">vjjmiras</a>*

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalco-website).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[content/OWNERS](https://github.com/falcosecurity/falco-website/blob/master/content/OWNERS)~~ [vjjmiras]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2023-07-10 12:13 UTC, poiana commented
LGTM label has been added.  <details>Git tree hash: 7cbb48f44e9e23555db1f84947fc7dae596cee2b</details>

2023-07-10 12:14 UTC, merged